console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 4
final_space = true

[transient_prompt]
foreground_templates = [
  "{{ if eq .Code 0 }}#@COLOR_GREEN@{{ end }}",
  "{{ if ne .Code 0 }}#@COLOR_RED@{{ end }}",
]
template = "❯ "

[secondary_prompt]
foreground = "#@COLOR_GREEN@"
template = "❯❯"

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = "os"
style = "plain"
foreground = "#@COLOR_FG@"
template = "{{ .Icon }} "

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "#@COLOR_BLUE@"
template = """
{{ if not .Writable }} {{ end }}\
{{ if .Segments.Git }}{{ .Folder }}\
{{ else }}{{ .Path }}{{ end }}\
"""

[blocks.segments.options]
style = "agnoster_full"
display_root = true

[blocks.segments.options.mapped_locations]
"re:^(/home/[^/]+)$" = ""

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "#@COLOR_GREEN@"
template = """ {{ .UpstreamIcon }} \
{{ .HEAD }}\
{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
{{ if gt .StashCount 0 }} *{{ .StashCount }}{{ end }}\
<#@COLOR_YELLOW@>{{ if .Staging.Changed }} [{{ .Staging.String }}]{{ end }}\
{{ if .Working.Changed }} {{ .Working.String }}{{ end }}</>\
"""

[blocks.segments.options]
fetch_status = true
fetch_upstream_icon = true
branch_icon = "\uf126 "
git_icon = "\ue702"
branch_identical_icon = ""
branch_gone_icon = ""


[[blocks]]
type = 'prompt'
alignment = "right"
overflow = "hidden"

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "#@COLOR_YELLOW@"
template = "\uf017 {{ .FormattedMs }} "

[[blocks.segments]]
type = "status"
style = "plain"
foreground = "#@COLOR_RED@"
template = "\u2718 {{ .Code }}"


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{ if eq .Code 0 }}#@COLOR_GREEN@{{ end }}",
  "{{ if ne .Code 0 }}#@COLOR_RED@{{ end }}",
]
template = "❯"
